Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
